### ISSUE TITLE
Please include the NEWS file in packages

### ISSUE THREAD

**Issue by sebix** [chaoss/grimoirelab-toolkit#1]
So downstream can ship it directly to the users next time :)

Thanks!

**Comment by sduenas** [comment]
You're right. I guess we aren't shipping it in any other Grimoire Lab package. Thanks!

**Comment by sduenas** [comment]
@jgbarah can you check this?

**Comment by jgbarah** [comment]
What do you mean by checking? Ensuring that we include a NEWS or CHANGELOG file? Or checking that other GrimoireLab tools are not shipping it? Or both?

[Just to clarify...]

**Comment by sebix** [comment]
The repository has a NEWS file, but it is not part of the sdist packages. This actually applies to all packages in this ecosystem, but this program was the first where I noticed it.

**Comment by jgbarah** [comment]
Thanks for the clarification. I will try to do that soon. Leaving this open meanwhile, assigning the ticket to myself.

**Comment by vchrombie** [comment]
We now have the NEWS file in the packages. We are gonna have them in the future too since we are using poetry to build packages and upload them to PyPI.

@jgbarah I think we can close this issue.
