### ISSUE TITLE
Support for Python 3.5

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-toolkit#28]
It seems that the change at https://github.com/chaoss/grimoirelab-toolkit/commit/6230394618eb077f5d2221be026c8e09dd951c52 has removed the support for Python 3.5.

The CI tests for https://github.com/chaoss/grimoirelab-elk/commit/5341e46d30b91bbc7eef304d1eee9477131e893a (which was committed before the change in toolkit) were successfully executed, while the next commits on ELK are failing with the following error message (refs [here](https://travis-ci.org/github/chaoss/grimoirelab-elk/jobs/717464287), [here](https://travis-ci.org/github/chaoss/grimoirelab-elk/builds/721557494) and [here](https://travis-ci.org/github/chaoss/grimoirelab-elk/builds/720970432)):
```
ERROR: Package 'grimoirelab-toolkit' requires a different Python: 3.5.6 not in '>=3.6,<4.0'
The command "pip install -r "requirements.txt"" failed and exited with 1 during .
```

**Comment by vchrombie** [comment]
I think we have fixed this error. The CI of all the GrimoireLab repositories has been shifted to GitHub Actions and all the builds are working fine.

Can we close this issue?

**Comment by sduenas** [comment]
Yes, let's close it.
