### ISSUE TITLE
No module named 'setuptools'

### ISSUE THREAD

**Issue by suhascv** [chaoss/grimoirelab-toolkit#33]
# Error while installing requirements from [perceval](https://github.com/chaoss/grimoirelab-perceval)
```pip3 install -r requirements.txt``` 

![Screenshot from 2021-02-24 10-00-13](https://user-images.githubusercontent.com/43292181/109019745-467a1300-7687-11eb-913d-a8140b685697.png)

**Comment by vchrombie** [comment]
I think this issue is fixed by the PR https://github.com/chaoss/grimoirelab-toolkit/pull/36

**Comment by vchrombie** [comment]
@suhascv, can you try to install perceval and confirm if this issue is fixed?

**Comment by suhascv** [comment]
@vchrombie sure

**Comment by suhascv** [comment]
@vchrombie  its working

**Comment by vchrombie** [comment]
Thanks @suhascv for confirming. 🙂
